#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb  1 17:03:46 2023

Generate two text files containing the cope files and EV matrix to be pasted
into the feat GUI for third-level analysis.

@author: jtm545
"""

import os
import os.path as op
import glob
import numpy as np

NCONTRASTS = 7
NSUBJECTS = 19

evs = np.tile(np.eye(NCONTRASTS, dtype=int), (NSUBJECTS, 1))

np.savetxt('./EV_paste.txt', evs, delimiter='\t', fmt='%i')

copes = glob.glob('./featout/R*.gfeat/cope?.feat/stats/cope*')

copes = sorted([op.abspath(c) for c in copes])

with open('copefiles.txt' , 'w') as f:
    for c in copes:
        f.write(c + '\n')