#!/usr/bin/env bash

# Rnumbers
rnumbers=/scratch/groups/Projects/P1470/fsl/RNUMBERS.txt

while read rnum; do
  for frun in {1..4}; do
    echo $rnum
    echo $frun
    # Modify the script
    sed -i.bak -E "s/R[0-9]{4}_FMRI_[0-9]/${rnum}_FMRI_${frun}/g" fsl_get_mask_ts
    # Send to cluster
    qsub -j y fsl_get_mask_ts
  done
done < "$rnumbers"
