#!/usr/bin/env bash

# Rnumbers
rnumbers=/scratch/groups/Projects/P1470/fsl/RNUMBERS.txt

while read rnum; do
  for frun in {1..4}; do
    echo $rnum
    echo $frun
    # Modify the script
    sed -i -E "s/R[0-9]{4}/${rnum}/g" fsl_resample_benson_v1
    sed -i -E "s/FMRI_[0-9]/FMRI_${frun}/g" fsl_resample_benson_v1

    # Send to cluster
    qsub -j y -o /scratch/home/j/jtm545/logs fsl_resample_benson_v1
  done
done < "$rnumbers"