#!/bin/bash

# View contrasts for third-level FEAT analysis
# Usage: ./viewgcon

path="./featout/group_level_3.gfeat"
echo $path

fsleyes --standard1mm \
  $path/cope1.feat/stats/zstat1 -un -cm brain_colours_1hot_iso -nc brain_colours_2winter_iso -dr 3 7 \
  $path/cope1.feat/stats/zstat2 -un -cm brain_colours_1hot_iso -nc brain_colours_2winter_iso -dr 3 7 \
  $path/cope1.feat/stats/zstat3 -un -cm brain_colours_1hot_iso -nc brain_colours_2winter_iso -dr 3 7 \
  $path/cope1.feat/stats/zstat4 -un -cm brain_colours_1hot_iso -nc brain_colours_2winter_iso -dr 3 7 \
  $path/cope1.feat/stats/zstat5 -un -cm brain_colours_1hot_iso -nc brain_colours_2winter_iso -dr 3 7 \
  $path/cope1.feat/stats/zstat6 -un -cm brain_colours_1hot_iso -nc brain_colours_2winter_iso -dr 3 7 \
  $path/cope1.feat/stats/zstat7 -un -cm brain_colours_1hot_iso -nc brain_colours_2winter_iso -dr 3 7 &
